### ISSUE TITLE
Faker.js a été hacké => lien à changer

### ISSUE THREAD

**Issue by nadlgit** [MikeCodeur/react-testing#3]
Info: https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected

Le projet a été repris par d'autres développeurs: https://fakerjs.dev/update.html

En utilisant la nouvelle version, il faut remplacer tous les imports par:
`import faker from '@faker-js/faker'`

**Comment by MikeCodeur** [comment]
Thanks, mergé et corrigé
