### ISSUE TITLE
"npm test" ne fonctionne pas

### ISSUE THREAD

**Issue by Aurelia77** [MikeCodeur/react-testing#6]
Bonjour, jusqu'ici tout fonctionnait bien, j'ai même réessayé avec le module précédent, aucun soucis.
Mais ici je n'ai pas pu lancer comme d'habitude NPM INSTALL puis START ( NPM RUN INIT n'a jamais fonctionné) mais Mike dit qu'on n'a pas besoin de lancer, donc j'ai fait directement NPM TEST mais voici l'erreur :
Merci d'avance.

_PS C:\Users\Aurélia HEYMANN\Aurélia\2022 Informatique\Formations\2023-02-REACT(MikeCodeur)\GitClones\react-testing> npm test
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> @mikecodeur/react-testing@1.0.0 test
> react-scripts test --env=jsdom

'react-scripts' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes._

**Comment by Aurelia77** [comment]
Et voici ce que j'ai quand je fais NPM INSTALL, si ça peut aider... Merci !

PS C:\Users\Aurélia HEYMANN\Aurélia\2022 Informatique\Formations\2023-02-REACT(MikeCodeur)\GitClones\react-testing> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @mikecodeur/react-testing@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-use-geolocation@0.1.1
npm ERR! node_modules/react-use-geolocation
npm ERR!   react-use-geolocation@"^0.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Aurélia HEYMANN\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aurélia HEYMANN\AppData\Local\npm-cache\_logs\2023-04-03T15_19_07_797Z-debug-0.log

**Comment by MikeCodeur** [comment]
@Aurelia77 Merci pour nous remonter ce problème. 

Peux tu nous dire si tu arrive a installer les autres modules correctement ? react-fondamentaux etc ... 

Peux tu nous dire ta version de 

- git
- node
- npm

Merci

**Comment by Aurelia77** [comment]
Hello Mike.
Oui tous les autres modules fonctionnaient bien, mais pas avec "npm run init", je devais faire à chaque fois "npm install" puis "npm start".
Voici les versions que j'ai : 
git version 2.39.1.windows.1
npm 8.11.0
Node.js v16.16.0.

Merci pour ton aide !

**Comment by Aurelia77** [comment]
J'ajoute aussi cette info si besoin...
Quand je fait "npm run init" voici l'erreur : (pourtant j'ai npm 8...)
Merci !

PS C:\Users\Aurélia HEYMANN\Aurélia\2022 Informatique\Formations\2023-02-REACT(MikeCodeur)\GitClones\6-react-hooks-avances> npm run init
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> @mikecodeur/react-hooks-avances@1.0.0 init
> node install

▶️  Démarrage de l'installation de l' environnement...
🚨  npx n'est pas disponible sur cet ordinateur. Merci d'installer npm@6.0.0 ou version plus récente

C:\Users\Aurélia HEYMANN\Aurélia\2022 Informatique\Formations\2023-02-REACT(MikeCodeur)\GitClones\6-react-hooks-avances\scripts\install.js:24
  throw error
  ^
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
(Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by Aurelia77** [comment]
Hello !
Je viens de passé 1h sur DISCORD, j'ai eu beaucoup d'aide mais ça ne fonctionne toujours pas...
On a résolu le WAR => cette ligne ne s'affiche plus => npm WARN config global --global, --local are deprecated. Use --location=global instead.
en modifiant 2 fichier NPM (apparemment ce n'est pas très bien de le faire...)
Mais les ERREURS sont toujours là :(
Merci d'avance !! :)

**Comment by Aurelia77** [comment]
En cherchant sur le WEB => npm ERR! Could not resolve dependency: "npm ERR! peer react@" 
J'ai trouvé ça :
This happens when you are trying to clone a project which is built a long time ago, and project dependencies have moved on to newer versions.
Just run below code. Works fine for me every time. You should also see this solution with the error.

 **npm install --legacy-peer-deps**

Et ça marche !!!!! :)

Ensuite j'ai fait NPM TEST => ok !!
Je clôture donc ce ticket, merci.
